[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SITE_URL = "https://nk-studio-clone.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
